---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages
    package:
      name: 
       - " {{apache_package }}"
       - "{{ php_package }}"
      state: latest
      lock_timeout: 180 # some issue about "yum lockfile is held by another process"
      update_cache: yes
