---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo index
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  tags: apache,http,apache2
  become: true
  roles:
    - web_servers

- hosts: db_servers
  tags: db,mariadb
  become: true
  roles:
    - db_servers

- hosts: workstations
  tags: workstation
  become: true
  roles:
    - workstations
