---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes 

  - name: uninstall apache
    apt:
      name: apache2
      state: absent

  - name: uninstall php support
    apt:
      name: libapache2-mod-php
      state: absent