- name: install apache and php
  package:
    name: 
      - "{{ apache_package}}"
      - "{{php_package}}"
    state: latest
- name: add default index
  copy:
    src: default_index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
- name: enable httpd service
  service:
   name: "{{ apache_service }}"
   state: started
   enabled: yes
- name: change admin email in conf file
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: ^ServerAdmin
    line: ServerAdmin miruna@someplace.net
  when: ansible_distribution == "CentOS"
  notify: restart_apache