- name: install unzip
  package:
    name: unzip
    state: latest
- name: install terraform from zip
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_386.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 755